openapi: 3.1.0
info:
  title: PDF Split API
  version: 1.0.0
  description: A simple API that accepts a PDF file and splits it into individual pages.
servers:
  - url: https://pdf-split-api.render.com  # Replace with your actual deployment URL
paths:
  /split:
    post:
      operationId: splitPdf
      summary: Split a PDF into individual pages.
      x-openai-isConsequential: false
      description: >
        Accepts a PDF file via multipart/form-data, splits it into single-page documents,
        and bundles them into a ZIP file.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The PDF file to be split.
      responses:
        '200':
          description: Successfully split PDF into a ZIP file containing individual pages.
          content:
            application/x-zip-compressed:
              schema:
                type: string
                format: binary
